### ISSUE TITLE
Screen recording issue

### ISSUE THREAD

**Issue by ja-som** [LineageOS/android_packages_apps_Recorder#2]
Hi,
I'm not sure if you can help me, if I'm in the right place.

I reported issue with screen recording on my Nexus 7 2013 Flo here:
https://jira.lineageos.org/browse/BUGBASH-25

It was marked as fixed, but it is not.

I compiled apk from sources here and I still have the same issue. Recordings are only few kB big.

**Comment by jesec** [comment]
If it is not fixed, reopen it on JIRA. We don't use Github Issues.

**Comment by ja-som** [comment]
OK, thanks.
